name: Daily LinkedIn Post (9am PST)

on:
  schedule:
    # 9am Pacific Standard Time; GitHub uses UTC, handle PST/PDT via two rules
    - cron: '0 17 * * *'   # 9am PST = 17:00 UTC when standard time
    - cron: '0 16 * * *'   # 9am PDT = 16:00 UTC when daylight time
  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Prepare environment
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_PERSON_ID: ${{ secrets.LINKEDIN_PERSON_ID }}
          POSTING_ENABLED: ${{ secrets.POSTING_ENABLED || 'false' }}
          NODE_ENV: production
          TIMEZONE: America/Los_Angeles
        run: |
          node -e "console.log('Env ready')"

      - name: Generate and post (once)
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_PERSON_ID: ${{ secrets.LINKEDIN_PERSON_ID }}
          POSTING_ENABLED: ${{ secrets.POSTING_ENABLED || 'false' }}
          NODE_ENV: production
          TIMEZONE: America/Los_Angeles
        run: node scheduler/daily-post-scheduler.js --once


